# Generated by Django on 2026-02-10
# Data migration to populate State, County, and PopulatedPlace from Location

from django.db import migrations

# US States and territories mapping
US_STATES = {
    "AL": "Alabama",
    "AK": "Alaska",
    "AZ": "Arizona",
    "AR": "Arkansas",
    "CA": "California",
    "CO": "Colorado",
    "CT": "Connecticut",
    "DE": "Delaware",
    "DC": "District of Columbia",
    "FL": "Florida",
    "GA": "Georgia",
    "HI": "Hawaii",
    "ID": "Idaho",
    "IL": "Illinois",
    "IN": "Indiana",
    "IA": "Iowa",
    "KS": "Kansas",
    "KY": "Kentucky",
    "LA": "Louisiana",
    "ME": "Maine",
    "MD": "Maryland",
    "MA": "Massachusetts",
    "MI": "Michigan",
    "MN": "Minnesota",
    "MS": "Mississippi",
    "MO": "Missouri",
    "MT": "Montana",
    "NE": "Nebraska",
    "NV": "Nevada",
    "NH": "New Hampshire",
    "NJ": "New Jersey",
    "NM": "New Mexico",
    "NY": "New York",
    "NC": "North Carolina",
    "ND": "North Dakota",
    "OH": "Ohio",
    "OK": "Oklahoma",
    "OR": "Oregon",
    "PA": "Pennsylvania",
    "RI": "Rhode Island",
    "SC": "South Carolina",
    "SD": "South Dakota",
    "TN": "Tennessee",
    "TX": "Texas",
    "UT": "Utah",
    "VT": "Vermont",
    "VA": "Virginia",
    "WA": "Washington",
    "WV": "West Virginia",
    "WI": "Wisconsin",
    "WY": "Wyoming",
    "AS": "American Samoa",
    "GU": "Guam",
    "MP": "Northern Mariana Islands",
    "PR": "Puerto Rico",
    "VI": "U.S. Virgin Islands",
}


def populate_states(apps, schema_editor):
    """Create all US states and territories."""
    State = apps.get_model("location", "State")

    for code, name in US_STATES.items():
        State.objects.get_or_create(code=code, defaults={"name": name})


def populate_counties_and_places(apps, schema_editor):
    """
    Extract unique counties and places from existing Location records.
    """
    Location = apps.get_model("location", "Location")
    State = apps.get_model("location", "State")
    County = apps.get_model("location", "County")
    PopulatedPlace = apps.get_model("location", "PopulatedPlace")

    # Get unique state codes from Location data and ensure they exist
    location_states = Location.objects.values_list("state", flat=True).distinct()
    for state_code in location_states:
        if state_code and state_code not in US_STATES:
            # Create state if not in standard list (handles edge cases)
            State.objects.get_or_create(
                code=state_code,
                defaults={"name": state_code},  # Use code as name if unknown
            )

    # Create counties from unique county_ahcb + state combinations
    county_cache = {}
    counties_data = (
        Location.objects.exclude(county_ahcb__isnull=True)
        .exclude(county_ahcb="")
        .values("county_ahcb", "county", "state")
        .distinct()
    )

    for data in counties_data:
        ahcb_id = data["county_ahcb"]
        county_name = data["county"]
        state_code = data["state"]

        if not ahcb_id or not state_code:
            continue

        try:
            state = State.objects.get(code=state_code)
        except State.DoesNotExist:
            continue

        county, created = County.objects.get_or_create(
            ahcb_id=ahcb_id, defaults={"name": county_name, "state": state}
        )
        county_cache[ahcb_id] = county

    # Create PopulatedPlace records from Location
    for location in Location.objects.all():
        if not location.county_ahcb:
            continue

        county = county_cache.get(location.county_ahcb)
        if not county:
            continue

        PopulatedPlace.objects.create(
            place_id=location.place_id,
            name=location.city or location.map_name or "Unknown",
            county=county,
            lat=location.lat,
            lon=location.lon,
            legacy_location_id=location.id,
        )


def reverse_migration(apps, schema_editor):
    """Remove all populated data."""
    PopulatedPlace = apps.get_model("location", "PopulatedPlace")
    County = apps.get_model("location", "County")
    State = apps.get_model("location", "State")

    PopulatedPlace.objects.all().delete()
    County.objects.all().delete()
    State.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0003_create_geographic_hierarchy"),
    ]

    operations = [
        migrations.RunPython(populate_states, reverse_migration),
        migrations.RunPython(populate_counties_and_places, migrations.RunPython.noop),
    ]
