# Generated by Django 5.1.5 on 2025-02-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0004_alter_city_name_alter_county_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="county",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="historicalcity",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="historicalcounty",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="historicalstate",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="historicalunlistedlocation",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="state",
            name="name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="unlistedlocation",
            name="name",
            field=models.CharField(max_length=500),
        ),
    ]
