# Generated by Django 5.1.5 on 2025-02-18 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0005_alter_city_name_alter_county_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CensusLocationMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("census_location_id", models.CharField(max_length=50, unique=True)),
                (
                    "census_address",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "unlisted_place",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.location",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["census_location_id"],
                        name="location_ce_census__87dc0e_idx",
                    )
                ],
            },
        ),
    ]
