# Generated by Django 5.1.5 on 2025-02-18 19:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0006_censuslocationmapping"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CensusLocationMapping",
        ),
    ]
