# Generated by Django 5.1.5 on 2025-03-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("location", "0007_delete_censuslocationmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicallocation",
            name="county_ahcb",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="historicallocation",
            name="map_name",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="location",
            name="county_ahcb",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="location",
            name="map_name",
            field=models.CharField(max_length=500),
        ),
    ]
