# Generated by Django 5.1.7 on 2025-09-09 20:35

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Page",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Page title (shown in browser tab and as heading)",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL path (e.g., 'datasets' for /datasets/). Leave blank to auto-generate from title.",
                        max_length=200,
                        unique=True,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Page content. HTML is allowed for formatting."
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description for search engines (160 characters max)",
                        max_length=160,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this page from public view",
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional: Schedule when this page should go live",
                        null=True,
                    ),
                ),
                (
                    "show_in_nav",
                    models.BooleanField(
                        default=False,
                        help_text="Check to show this page in the main navigation menu",
                    ),
                ),
                (
                    "nav_title",
                    models.CharField(
                        blank=True,
                        help_text="Short title for navigation (leave blank to use main title)",
                        max_length=50,
                    ),
                ),
                (
                    "nav_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in navigation menu (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Page",
                "verbose_name_plural": "Pages",
                "ordering": ["nav_order", "title"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Page title (shown in browser tab and as heading)",
                        max_length=200,
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL path (e.g., 'datasets' for /datasets/). Leave blank to auto-generate from title.",
                        max_length=200,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="Page content. HTML is allowed for formatting."
                    ),
                ),
                (
                    "meta_description",
                    models.CharField(
                        blank=True,
                        help_text="Brief description for search engines (160 characters max)",
                        max_length=160,
                    ),
                ),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Uncheck to hide this page from public view",
                    ),
                ),
                (
                    "publish_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Optional: Schedule when this page should go live",
                        null=True,
                    ),
                ),
                (
                    "show_in_nav",
                    models.BooleanField(
                        default=False,
                        help_text="Check to show this page in the main navigation menu",
                    ),
                ),
                (
                    "nav_title",
                    models.CharField(
                        blank=True,
                        help_text="Short title for navigation (leave blank to use main title)",
                        max_length=50,
                    ),
                ),
                (
                    "nav_order",
                    models.IntegerField(
                        default=0,
                        help_text="Order in navigation menu (lower numbers appear first)",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Page",
                "verbose_name_plural": "historical Pages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
