# Generated by Django 5.1.7 on 2026-01-23 15:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("author", models.CharField(max_length=200)),
                ("published_date", models.DateTimeField()),
                ("content", models.TextField(help_text="Markdown content")),
                ("abstract", models.TextField(blank=True)),
                (
                    "featured_image",
                    models.CharField(
                        blank=True, help_text="Path to featured image", max_length=500
                    ),
                ),
                ("image_alt_text", models.CharField(blank=True, max_length=500)),
                ("is_draft", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Visualization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("published_date", models.DateTimeField()),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField(help_text="Markdown content")),
                ("abstract", models.TextField()),
                (
                    "thumbnail",
                    models.CharField(
                        help_text="Path to thumbnail image", max_length=500
                    ),
                ),
                ("thumbnail_description", models.CharField(blank=True, max_length=500)),
                (
                    "doi",
                    models.URLField(blank=True, help_text="Digital Object Identifier"),
                ),
                (
                    "script_file",
                    models.CharField(
                        help_text="Path to JavaScript file (e.g., viz/cities-map/main.js)",
                        max_length=200,
                    ),
                ),
                (
                    "style_file",
                    models.CharField(
                        help_text="Path to CSS file (e.g., viz/cities-map/style.css)",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Visualization",
                "verbose_name_plural": "Visualizations",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalBlogPost",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=200)),
                ("author", models.CharField(max_length=200)),
                ("published_date", models.DateTimeField()),
                ("content", models.TextField(help_text="Markdown content")),
                ("abstract", models.TextField(blank=True)),
                (
                    "featured_image",
                    models.CharField(
                        blank=True, help_text="Path to featured image", max_length=500
                    ),
                ),
                ("image_alt_text", models.CharField(blank=True, max_length=500)),
                ("is_draft", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Blog Post",
                "verbose_name_plural": "historical Blog Posts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalVisualization",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("slug", models.SlugField(max_length=200)),
                ("published_date", models.DateTimeField()),
                ("updated_date", models.DateTimeField(blank=True, null=True)),
                ("content", models.TextField(help_text="Markdown content")),
                ("abstract", models.TextField()),
                (
                    "thumbnail",
                    models.CharField(
                        help_text="Path to thumbnail image", max_length=500
                    ),
                ),
                ("thumbnail_description", models.CharField(blank=True, max_length=500)),
                (
                    "doi",
                    models.URLField(blank=True, help_text="Digital Object Identifier"),
                ),
                (
                    "script_file",
                    models.CharField(
                        help_text="Path to JavaScript file (e.g., viz/cities-map/main.js)",
                        max_length=200,
                    ),
                ),
                (
                    "style_file",
                    models.CharField(
                        help_text="Path to CSS file (e.g., viz/cities-map/style.css)",
                        max_length=200,
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Visualization",
                "verbose_name_plural": "historical Visualizations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
