# Generated by Django 5.2.8 on 2026-01-26 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0003_page_historicalpage"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpost",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image for blog post listings",
                null=True,
                upload_to="blog/thumbnails/",
            ),
        ),
        migrations.AddField(
            model_name="historicalblogpost",
            name="thumbnail_image",
            field=models.TextField(
                blank=True,
                help_text="Thumbnail image for blog post listings",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="historicalvisualization",
            name="thumbnail_image",
            field=models.TextField(
                blank=True,
                help_text="Thumbnail image for visualization listings",
                max_length=100,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="visualization",
            name="thumbnail_image",
            field=models.ImageField(
                blank=True,
                help_text="Thumbnail image for visualization listings",
                null=True,
                upload_to="visualizations/thumbnails/",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Path to featured image (use thumbnail_image instead)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="historicalblogpost",
            name="featured_image",
            field=models.CharField(
                blank=True,
                help_text="DEPRECATED: Path to featured image (use thumbnail_image instead)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="historicalvisualization",
            name="thumbnail",
            field=models.CharField(
                help_text="DEPRECATED: Path to thumbnail image (use thumbnail_image instead)",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="thumbnail",
            field=models.CharField(
                help_text="DEPRECATED: Path to thumbnail image (use thumbnail_image instead)",
                max_length=500,
            ),
        ),
    ]
