# Generated by Django 5.2.8 on 2026-01-26 15:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0004_blogpost_thumbnail_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalvisualization",
            name="author",
            field=models.CharField(
                blank=True, help_text="Author(s) of the visualization", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="visualization",
            name="author",
            field=models.CharField(
                blank=True, help_text="Author(s) of the visualization", max_length=200
            ),
        ),
    ]
