# Generated by Django 6.0.1 on 2026-02-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0005_historicalvisualization_author_visualization_author"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalvisualization",
            name="thumbnail",
        ),
        migrations.RemoveField(
            model_name="visualization",
            name="thumbnail",
        ),
        migrations.AlterField(
            model_name="historicalvisualization",
            name="script_file",
            field=models.CharField(
                blank=True,
                help_text="Path to JavaScript file (e.g., viz/cities-map/main.js)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalvisualization",
            name="style_file",
            field=models.CharField(
                blank=True,
                help_text="Path to CSS file (e.g., viz/cities-map/style.css)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="script_file",
            field=models.CharField(
                blank=True,
                help_text="Path to JavaScript file (e.g., viz/cities-map/main.js)",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="visualization",
            name="style_file",
            field=models.CharField(
                blank=True,
                help_text="Path to CSS file (e.g., viz/cities-map/style.css)",
                max_length=200,
                null=True,
            ),
        ),
    ]
