# Generated by Django 6.0.1 on 2026-02-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pages', '0006_remove_historicalvisualization_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpage',
            name='content',
            field=models.TextField(help_text='Page content as Markdown. HTML is allowed for formatting.'),
        ),
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(help_text='Page content as Markdown. HTML is allowed for formatting.'),
        ),
    ]
