# Generated by Django 6.0.5 on 2026-07-09 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("pages", "0007_alter_historicalpage_content_alter_page_content"),
        ("visualizations", "0002_migrate_data"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalvisualization",
            name="history_user",
        ),
        migrations.DeleteModel(
            name="Visualization",
        ),
        migrations.DeleteModel(
            name="HistoricalVisualization",
        ),
    ]
