# Generated by Django 5.1.4 on 2024-12-19 19:31

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Denomination",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="HistoricalDenomination",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(db_index=True, max_length=50)),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical denomination",
                "verbose_name_plural": "historical denominations",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalReligiousCensusRecord",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("resource_id", models.IntegerField(db_index=True)),
                ("schedule_title", models.CharField(max_length=255)),
                ("schedule_id", models.IntegerField()),
                (
                    "datascribe_omeka_item_id",
                    models.IntegerField(
                        help_text="This record is read-only and not editable.",
                        verbose_name="DataScribe Omeka Item ID",
                    ),
                ),
                (
                    "datascribe_item_id",
                    models.IntegerField(
                        help_text="This record is read-only and not editable.",
                        verbose_name="DataScribe Item ID",
                    ),
                ),
                (
                    "datascribe_record_id",
                    models.IntegerField(
                        help_text="This record is read-only and not editable.",
                        verbose_name="DataScribe Record ID",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "denomination",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="census.denomination",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical religious census record",
                "verbose_name_plural": "historical religious census records",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReligiousCensusRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("resource_id", models.IntegerField(unique=True)),
                ("schedule_title", models.CharField(max_length=255)),
                ("schedule_id", models.IntegerField()),
                (
                    "datascribe_omeka_item_id",
                    models.IntegerField(
                        help_text="This record is read-only and not editable.",
                        verbose_name="DataScribe Omeka Item ID",
                    ),
                ),
                (
                    "datascribe_item_id",
                    models.IntegerField(
                        help_text="This record is read-only and not editable.",
                        verbose_name="DataScribe Item ID",
                    ),
                ),
                (
                    "datascribe_record_id",
                    models.IntegerField(
                        help_text="This record is read-only and not editable.",
                        verbose_name="DataScribe Record ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "denomination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="census.denomination",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["schedule_id"], name="census_reli_schedul_855e64_idx"
                    ),
                    models.Index(
                        fields=["datascribe_omeka_item_id"],
                        name="census_reli_datascr_9e11fd_idx",
                    ),
                ],
            },
        ),
    ]
