# Generated by Django 5.1.4 on 2024-12-19 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreligiouscensusrecord",
            name="schedule_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="religiouscensusrecord",
            name="schedule_id",
            field=models.CharField(max_length=50),
        ),
    ]
