# Generated by Django 5.1.7 on 2025-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denomination",
            name="family_arda",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="denomination",
            name="family_census",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldenomination",
            name="family_arda",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicaldenomination",
            name="family_census",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
