# Generated by Django 5.1.7 on 2025-05-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0002_alter_denomination_family_arda_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="denomination",
            name="denomination_id",
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="historicaldenomination",
            name="denomination_id",
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
