# Generated by Django 5.1.7 on 2025-05-16 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0003_alter_denomination_denomination_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="denomination",
            name="short_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicaldenomination",
            name="short_name",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
