# Generated by Django 5.1.5 on 2025-02-13 16:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0004_clergy_census_schedule_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="censusschedule",
            name="benevolences",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="expenses",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="parochial_num_administrators",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="parochial_num_elementary_scholars",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="parochial_num_elementary_teachers",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="parochial_num_secondary_scholars",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="parochial_num_secondary_teachers",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="sunday_school_num_officers_teachers",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="sunday_school_num_scholars",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="total_expenditures",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="vbs_num_officers_teachers",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="vbs_num_scholars",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="benevolences",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="expenses",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="parochial_num_administrators",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="parochial_num_elementary_scholars",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="parochial_num_elementary_teachers",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="parochial_num_secondary_scholars",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="parochial_num_secondary_teachers",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="sunday_school_num_officers_teachers",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="sunday_school_num_scholars",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="total_expenditures",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="vbs_num_officers_teachers",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="vbs_num_scholars",
        ),
        migrations.AddField(
            model_name="church",
            name="benevolences",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="church",
            name="expenses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="church",
            name="total_expenditures",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="historicalchurch",
            name="benevolences",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="historicalchurch",
            name="expenses",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="historicalchurch",
            name="total_expenditures",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="parochial_num_administrators",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="parochial_num_elementary_scholars",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="parochial_num_elementary_teachers",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="parochial_num_secondary_scholars",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="parochial_num_secondary_teachers",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="sunday_school_num_officers_teachers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="sunday_school_num_scholars",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="vbs_num_officers_teachers",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="vbs_num_scholars",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="parochial_num_administrators",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="parochial_num_elementary_scholars",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="parochial_num_elementary_teachers",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="parochial_num_secondary_scholars",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="parochial_num_secondary_teachers",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="sunday_school_num_officers_teachers",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="membership",
            name="sunday_school_num_scholars",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="membership",
            name="vbs_num_officers_teachers",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name="membership",
            name="vbs_num_scholars",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
    ]
