# Generated by Django 5.1.7 on 2025-05-16 16:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0004_denomination_short_name_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="denomination",
            old_name="family_arda",
            new_name="family_relec",
        ),
        migrations.RenameField(
            model_name="historicaldenomination",
            old_name="family_arda",
            new_name="family_relec",
        ),
    ]
