# Generated by Django 5.1.7 on 2025-05-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0005_rename_family_arda_denomination_family_relec_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="census_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="census_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
