# Generated by Django 5.1.5 on 2025-02-14 12:52

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0005_remove_censusschedule_benevolences_and_more"),
        ("location", "0003_alter_city_name_alter_county_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="church",
            name="census_record",
        ),
        migrations.RemoveField(
            model_name="church",
            name="location",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="denomination",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="location",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="denomination",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="location",
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="female_members",
            field=models.PositiveIntegerField(default=0, verbose_name="Female Members"),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="male_members",
            field=models.PositiveIntegerField(default=0, verbose_name="Male Members"),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="members_13_and_older",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Members 13 and Older"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="members_under_13",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Members Under 13"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_administrators",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Administrators"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_elementary_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Elementary Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_elementary_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Elementary Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_secondary_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Secondary Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_secondary_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Secondary Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="sunday_school_num_officers_teachers",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Officers/Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="sunday_school_num_scholars",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="vbs_num_officers_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Officers/Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="vbs_num_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="female_members",
            field=models.PositiveIntegerField(default=0, verbose_name="Female Members"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="male_members",
            field=models.PositiveIntegerField(default=0, verbose_name="Male Members"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="members_13_and_older",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Members 13 and Older"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="members_under_13",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Members Under 13"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_administrators",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Administrators"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_elementary_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Elementary Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_elementary_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Elementary Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_secondary_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Secondary Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_secondary_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Secondary Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="sunday_school_num_officers_teachers",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Officers/Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="sunday_school_num_scholars",
            field=models.PositiveIntegerField(
                default=0, verbose_name="Number of Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="vbs_num_officers_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Officers/Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="vbs_num_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Scholars"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalReligiousBody",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the church as it appears in the census record.",
                        max_length=255,
                        verbose_name="Local Church Name",
                    ),
                ),
                ("census_code", models.CharField(max_length=50)),
                ("division", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("urban_rural_code", models.CharField(max_length=50)),
                (
                    "num_edifices",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "edifice_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "edifice_debt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("has_pastors_residence", models.BooleanField(default=False)),
                (
                    "residence_value",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "residence_debt",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "benevolences",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_expenditures",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "census_record",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="census.censusschedule",
                    ),
                ),
                (
                    "denomination",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        help_text="Selec the denomination associated with this religious body.",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="census.denomination",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="location.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical Religious Body",
                "verbose_name_plural": "historical Religious Bodies",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ReligiousBody",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the church as it appears in the census record.",
                        max_length=255,
                        verbose_name="Local Church Name",
                    ),
                ),
                ("census_code", models.CharField(max_length=50)),
                ("division", models.CharField(max_length=100)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("urban_rural_code", models.CharField(max_length=50)),
                (
                    "num_edifices",
                    models.PositiveIntegerField(blank=True, default=0, null=True),
                ),
                (
                    "edifice_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "edifice_debt",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("has_pastors_residence", models.BooleanField(default=False)),
                (
                    "residence_value",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "residence_debt",
                    models.DecimalField(decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "expenses",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "benevolences",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_expenditures",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "census_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="church_details",
                        to="census.censusschedule",
                    ),
                ),
                (
                    "denomination",
                    models.ForeignKey(
                        help_text="Selec the denomination associated with this religious body.",
                        on_delete=django.db.models.deletion.PROTECT,
                        to="census.denomination",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="location.location",
                    ),
                ),
            ],
            options={
                "verbose_name": "Religious Body",
                "verbose_name_plural": "Religious Bodies",
            },
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="church",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="census.religiousbody",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="church",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership",
                to="census.religiousbody",
            ),
        ),
        migrations.DeleteModel(
            name="HistoricalChurch",
        ),
        migrations.DeleteModel(
            name="Church",
        ),
    ]
