# Generated by Django 5.1.5 on 2025-02-18 14:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0006_remove_church_census_record_remove_church_location_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="census_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_details",
                to="census.censusschedule",
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="census_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="church_details",
                to="census.censusschedule",
                unique=True,
            ),
        ),
    ]
