# Generated by Django 5.1.7 on 2025-05-21 18:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0006_alter_historicalreligiousbody_census_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="division",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="division",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
