# Generated by Django 5.1.7 on 2025-11-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0007_alter_historicalreligiousbody_division_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalreligiousbody",
            name="geocode_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending Geocoding"),
                    ("success", "Successfully Geocoded"),
                    ("failed", "Geocoding Failed"),
                    ("skipped", "Skipped (No Address)"),
                ],
                help_text="Status of automatic geocoding process.",
                max_length=20,
                null=True,
                verbose_name="Geocode Status",
            ),
        ),
        migrations.AddField(
            model_name="historicalreligiousbody",
            name="geocoded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when geocoding was last attempted.",
                null=True,
                verbose_name="Geocoded At",
            ),
        ),
        migrations.AddField(
            model_name="historicalreligiousbody",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Automatically geocoded from address. Leave blank to auto-geocode on save.",
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="historicalreligiousbody",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Automatically geocoded from address. Leave blank to auto-geocode on save.",
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AddField(
            model_name="religiousbody",
            name="geocode_status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("pending", "Pending Geocoding"),
                    ("success", "Successfully Geocoded"),
                    ("failed", "Geocoding Failed"),
                    ("skipped", "Skipped (No Address)"),
                ],
                help_text="Status of automatic geocoding process.",
                max_length=20,
                null=True,
                verbose_name="Geocode Status",
            ),
        ),
        migrations.AddField(
            model_name="religiousbody",
            name="geocoded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Timestamp when geocoding was last attempted.",
                null=True,
                verbose_name="Geocoded At",
            ),
        ),
        migrations.AddField(
            model_name="religiousbody",
            name="latitude",
            field=models.FloatField(
                blank=True,
                help_text="Automatically geocoded from address. Leave blank to auto-geocode on save.",
                null=True,
                verbose_name="Latitude",
            ),
        ),
        migrations.AddField(
            model_name="religiousbody",
            name="longitude",
            field=models.FloatField(
                blank=True,
                help_text="Automatically geocoded from address. Leave blank to auto-geocode on save.",
                null=True,
                verbose_name="Longitude",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="has_pastors_residence",
            field=models.BooleanField(
                blank=True,
                help_text="Set to Unknown if missing, illegible, or unknown.",
                null=True,
                verbose_name="Ownership of pastor's residence",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="has_pastors_residence",
            field=models.BooleanField(
                blank=True,
                help_text="Set to Unknown if missing, illegible, or unknown.",
                null=True,
                verbose_name="Ownership of pastor's residence",
            ),
        ),
    ]
