# Generated by Django 5.1.7 on 2025-08-25 20:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0007_alter_historicalreligiousbody_division_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="censusschedule",
            name="original_image",
            field=models.ImageField(
                blank=True,
                help_text="High-resolution image of the original census schedule",
                null=True,
                upload_to="census_images/originals/",
                verbose_name="Original Census Schedule Image",
            ),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="original_image",
            field=models.TextField(
                blank=True,
                help_text="High-resolution image of the original census schedule",
                max_length=100,
                null=True,
                verbose_name="Original Census Schedule Image",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="has_pastors_residence",
            field=models.BooleanField(
                blank=True,
                help_text="Set to Unknown if missing, illegible, or unknown.",
                null=True,
                verbose_name="Ownership of pastor's residence",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="has_pastors_residence",
            field=models.BooleanField(
                blank=True,
                help_text="Set to Unknown if missing, illegible, or unknown.",
                null=True,
                verbose_name="Ownership of pastor's residence",
            ),
        ),
    ]
