# Generated by Django 5.1.7 on 2026-01-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0007_alter_historicalreligiousbody_division_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="has_pastors_residence",
            field=models.BooleanField(
                blank=True,
                help_text="Set to Unknown if missing, illegible, or unknown.",
                null=True,
                verbose_name="Ownership of pastor's residence",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="has_pastors_residence",
            field=models.BooleanField(
                blank=True,
                help_text="Set to Unknown if missing, illegible, or unknown.",
                null=True,
                verbose_name="Ownership of pastor's residence",
            ),
        ),
    ]
