# Generated by Django 5.1.5 on 2025-02-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0008_alter_membership_census_record_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="membership",
            name="census_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_details",
                to="census.censusschedule",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="church",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership",
                to="census.religiousbody",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="census_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="church_details",
                to="census.censusschedule",
            ),
        ),
    ]
