# Generated by Django 5.1.7 on 2025-09-18 20:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0008_censusschedule_original_image_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="original_image",
        ),
        migrations.AddField(
            model_name="censusschedule",
            name="assigned_reviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Reviewer",
            ),
        ),
        migrations.AddField(
            model_name="censusschedule",
            name="assigned_transcriber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_transcriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Transcriber",
            ),
        ),
        migrations.AddField(
            model_name="censusschedule",
            name="transcription_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes about the transcription process or issues",
                null=True,
                verbose_name="Transcription Notes",
            ),
        ),
        migrations.AddField(
            model_name="censusschedule",
            name="transcription_status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("needs_review", "Needs Review"),
                    ("completed", "Transcribed"),
                    ("approved", "Approved"),
                ],
                default="unassigned",
                max_length=20,
                verbose_name="Transcription Status",
            ),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="assigned_reviewer",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Reviewer",
            ),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="assigned_transcriber",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Assigned Transcriber",
            ),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="transcription_notes",
            field=models.TextField(
                blank=True,
                help_text="Notes about the transcription process or issues",
                null=True,
                verbose_name="Transcription Notes",
            ),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="transcription_status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("needs_review", "Needs Review"),
                    ("completed", "Transcribed"),
                    ("approved", "Approved"),
                ],
                default="unassigned",
                max_length=20,
                verbose_name="Transcription Status",
            ),
        ),
    ]
