# Generated by Django 5.1.7 on 2025-09-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0009_remove_historicalcensusschedule_original_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censusschedule",
            name="datascribe_item_id",
            field=models.IntegerField(
                blank=True,
                help_text="This record is read-only and not editable.",
                null=True,
                verbose_name="DataScribe Item ID",
            ),
        ),
        migrations.AlterField(
            model_name="censusschedule",
            name="datascribe_omeka_item_id",
            field=models.IntegerField(
                blank=True,
                help_text="This record is read-only and not editable.",
                null=True,
                verbose_name="DataScribe Omeka Item ID",
            ),
        ),
        migrations.AlterField(
            model_name="censusschedule",
            name="datascribe_original_image_path",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="DataScribe Original Image Path",
            ),
        ),
        migrations.AlterField(
            model_name="censusschedule",
            name="datascribe_record_id",
            field=models.IntegerField(
                blank=True,
                help_text="This record is read-only and not editable.",
                null=True,
                verbose_name="DataScribe Record ID",
            ),
        ),
        migrations.AlterField(
            model_name="censusschedule",
            name="omeka_storage_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Omeka Storage ID"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="datascribe_item_id",
            field=models.IntegerField(
                blank=True,
                help_text="This record is read-only and not editable.",
                null=True,
                verbose_name="DataScribe Item ID",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="datascribe_omeka_item_id",
            field=models.IntegerField(
                blank=True,
                help_text="This record is read-only and not editable.",
                null=True,
                verbose_name="DataScribe Omeka Item ID",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="datascribe_original_image_path",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="DataScribe Original Image Path",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="datascribe_record_id",
            field=models.IntegerField(
                blank=True,
                help_text="This record is read-only and not editable.",
                null=True,
                verbose_name="DataScribe Record ID",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="omeka_storage_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Omeka Storage ID"
            ),
        ),
    ]
