# Generated by Django 5.1.5 on 2025-02-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0009_alter_membership_census_record_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalmembership",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Membership",
                "verbose_name_plural": "historical Membership",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreligiousbody",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Religious Body",
                "verbose_name_plural": "historical Religious Body",
            },
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={"verbose_name": "Membership", "verbose_name_plural": "Membership"},
        ),
        migrations.AlterModelOptions(
            name="religiousbody",
            options={
                "verbose_name": "Religious Body",
                "verbose_name_plural": "Religious Body",
            },
        ),
        migrations.AddField(
            model_name="censusschedule",
            name="datascribe_original_image_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="datascribe_original_image_path",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="num_edifices",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Number of edifices"
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="urban_rural_code",
            field=models.CharField(max_length=50, verbose_name="Urban/rural code"),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="num_edifices",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Number of edifices"
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="urban_rural_code",
            field=models.CharField(max_length=50, verbose_name="Urban/rural code"),
        ),
    ]
