# Generated by Django 5.2.8 on 2026-01-23 15:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0008_alter_historicalreligiousbody_has_pastors_residence_and_more"),
        ("census", "0010_alter_censusschedule_datascribe_item_id_and_more"),
    ]

    operations = []
