# Generated by Django 5.1.5 on 2025-02-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0010_alter_historicalmembership_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censusschedule",
            name="datascribe_original_image_path",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="DataScribe Original Image Path",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="datascribe_original_image_path",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="DataScribe Original Image Path",
            ),
        ),
    ]
