# Generated by Django 5.1.7 on 2025-10-20 15:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0010_alter_censusschedule_datascribe_item_id_and_more"),
        ("location", "0002_alter_historicallocation_place_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="censusschedule",
            index=models.Index(
                fields=["transcription_status"], name="census_cens_transcr_590370_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="censusschedule",
            index=models.Index(
                fields=["assigned_transcriber"], name="census_cens_assigne_4bf3ed_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="censusschedule",
            index=models.Index(
                fields=["assigned_reviewer"], name="census_cens_assigne_b92dbe_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="censusschedule",
            index=models.Index(
                fields=["transcription_status", "assigned_transcriber"],
                name="census_status_transcriber_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="clergy",
            index=models.Index(
                fields=["census_schedule"], name="census_cler_census__7ee1b2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clergy",
            index=models.Index(
                fields=["is_assistant"], name="census_cler_is_assi_1e1e9a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["census_record"], name="census_memb_census__f12410_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["religious_body"], name="census_memb_religio_39b36e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="membership",
            index=models.Index(
                fields=["census_record", "religious_body"],
                name="census_mem_census_rb_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="religiousbody",
            index=models.Index(
                fields=["census_record"], name="census_reli_census__01a20c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="religiousbody",
            index=models.Index(
                fields=["census_record", "denomination"],
                name="census_rb_census_denom_idx",
            ),
        ),
    ]
