# Generated by Django 5.1.7 on 2025-11-18 14:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0008_historicalreligiousbody_geocode_status_and_more"),
        ("census", "0011_add_performance_indexes"),
    ]

    operations = []
