# Generated by Django 5.1.5 on 2025-02-18 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0011_alter_censusschedule_datascribe_original_image_path_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="censusschedule",
            name="box",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="censusschedule",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="censusschedule",
            name="omeka_storage_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Omeka Storage ID"
            ),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="box",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="omeka_storage_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Omeka Storage ID"
            ),
        ),
    ]
