# Generated by Django 5.1.5 on 2025-02-18 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0012_censusschedule_box_censusschedule_notes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censusschedule",
            name="datascribe_original_image_path",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="DataScribe Original Image Path",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="censusschedule",
            name="omeka_storage_id",
            field=models.CharField(
                default="", max_length=255, verbose_name="Omeka Storage ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="clergy",
            name="num_other_churches_served",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="datascribe_original_image_path",
            field=models.CharField(
                default="",
                max_length=255,
                verbose_name="DataScribe Original Image Path",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="omeka_storage_id",
            field=models.CharField(
                default="", max_length=255, verbose_name="Omeka Storage ID"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="historicalclergy",
            name="num_other_churches_served",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="female_members",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Female Members"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="members_13_and_older",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Members 13 and Older"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="members_under_13",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Members Under 13"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="sunday_school_num_officers_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Officers/Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="sunday_school_num_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="urban_rural_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Urban/rural code"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="female_members",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Female Members"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="members_13_and_older",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Members 13 and Older"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="members_under_13",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Members Under 13"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="sunday_school_num_officers_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Officers/Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="sunday_school_num_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="urban_rural_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Urban/rural code"
            ),
        ),
    ]
