# Generated by Django 6.0.1 on 2026-02-03 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0011_merge_20260123_1548'),
        ('census', '0012_merge_20251118_1448'),
    ]

    operations = [
    ]
