# Generated by Django 6.0.1 on 2026-02-10 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0013_merge_20260203_1615"),
        ("location", "0004_populate_geographic_hierarchy"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="censusschedule",
            name="county",
            field=models.ForeignKey(
                blank=True,
                help_text="The county where this census was taken",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="census_schedules",
                to="location.county",
                verbose_name="County",
            ),
        ),
        migrations.AddField(
            model_name="censusschedule",
            name="populated_place",
            field=models.ForeignKey(
                blank=True,
                help_text="The specific city/town where this census was taken (optional)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="census_schedules",
                to="location.populatedplace",
                verbose_name="Populated Place",
            ),
        ),
        migrations.AddField(
            model_name="censusschedule",
            name="schedule_denomination",
            field=models.ForeignKey(
                blank=True,
                help_text="The denomination associated with this census schedule",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="census_schedules",
                to="census.denomination",
                verbose_name="Denomination",
            ),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="county",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The county where this census was taken",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="location.county",
                verbose_name="County",
            ),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="populated_place",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The specific city/town where this census was taken (optional)",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="location.populatedplace",
                verbose_name="Populated Place",
            ),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="schedule_denomination",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="The denomination associated with this census schedule",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="census.denomination",
                verbose_name="Denomination",
            ),
        ),
        migrations.AddIndex(
            model_name="censusschedule",
            index=models.Index(
                fields=["county"], name="census_cens_county__2cb172_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="censusschedule",
            index=models.Index(
                fields=["populated_place"], name="census_cens_populat_cfede1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="censusschedule",
            index=models.Index(
                fields=["schedule_denomination"], name="census_cens_schedul_7cad22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="censusschedule",
            index=models.Index(
                fields=["county", "schedule_denomination"],
                name="census_county_denom_idx",
            ),
        ),
    ]
