# Generated by Django 5.1.5 on 2025-02-18 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0014_alter_historicalreligiousbody_name_and_more"),
        ("location", "0007_delete_censuslocationmapping"),
    ]

    operations = [
        migrations.AlterField(
            model_name="religiousbody",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.location",
            ),
        ),
    ]
