# Generated by Django on 2026-02-10
# Data migration to copy location and denomination data from ReligiousBody to CensusSchedule

from django.db import migrations


def copy_location_data(apps, schema_editor):
    """
    For each CensusSchedule with a ReligiousBody:
    1. Copy ReligiousBody.denomination -> CensusSchedule.schedule_denomination
    2. Lookup PopulatedPlace by ReligiousBody.location (via legacy_location_id)
    3. Set CensusSchedule.populated_place and CensusSchedule.county
    """
    CensusSchedule = apps.get_model("census", "CensusSchedule")
    ReligiousBody = apps.get_model("census", "ReligiousBody")
    PopulatedPlace = apps.get_model("location", "PopulatedPlace")

    # Build a lookup cache for PopulatedPlace by legacy_location_id
    place_cache = {}
    for place in PopulatedPlace.objects.select_related("county").all():
        if place.legacy_location_id:
            place_cache[place.legacy_location_id] = place

    # Process each CensusSchedule
    schedules_to_update = []
    for schedule in CensusSchedule.objects.all():
        # Get the first ReligiousBody for this schedule (if any)
        religious_body = (
            ReligiousBody.objects.filter(census_record=schedule)
            .select_related("denomination", "location")
            .first()
        )

        if not religious_body:
            continue

        updated = False

        # Copy denomination
        if religious_body.denomination and not schedule.schedule_denomination:
            schedule.schedule_denomination = religious_body.denomination
            updated = True

        # Lookup and set location
        if religious_body.location_id:
            place = place_cache.get(religious_body.location_id)
            if place:
                if not schedule.populated_place:
                    schedule.populated_place = place
                    updated = True
                if not schedule.county:
                    schedule.county = place.county
                    updated = True

        if updated:
            schedules_to_update.append(schedule)

    # Bulk update
    if schedules_to_update:
        CensusSchedule.objects.bulk_update(
            schedules_to_update,
            ["schedule_denomination", "populated_place", "county"],
            batch_size=1000,
        )


def reverse_migration(apps, schema_editor):
    """Clear the copied location data."""
    CensusSchedule = apps.get_model("census", "CensusSchedule")
    CensusSchedule.objects.all().update(
        schedule_denomination=None, populated_place=None, county=None
    )


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0014_add_schedule_location_fields"),
        ("location", "0004_populate_geographic_hierarchy"),
    ]

    operations = [
        migrations.RunPython(copy_location_data, reverse_migration),
    ]
