# Generated by Django 6.0.1 on 2026-02-19 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0015_copy_location_to_schedule'),
        ('location', '0004_populate_geographic_hierarchy'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='religiousbody',
            name='census_reli_locatio_f3c697_idx',
        ),
        migrations.RemoveField(
            model_name='historicalreligiousbody',
            name='location',
        ),
        migrations.AlterField(
            model_name='censusschedule',
            name='populated_place',
            field=models.ForeignKey(blank=True, help_text='The specific city/town where this census was taken as city, county, state (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='census_schedules', to='location.populatedplace', verbose_name='Populated Place'),
        ),
        migrations.AlterField(
            model_name='historicalcensusschedule',
            name='populated_place',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The specific city/town where this census was taken as city, county, state (optional)', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='location.populatedplace', verbose_name='Populated Place'),
        ),
        migrations.RemoveField(
            model_name='religiousbody',
            name='location',
        ),
    ]
