# Generated by Django 5.1.5 on 2025-03-24 18:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0016_remove_religiousbody_census_record_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="censusschedule",
            name="box",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="box",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
