# Generated by Django 6.0.1 on 2026-03-16 12:38

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0016_remove_religiousbody_census_reli_locatio_f3c697_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DenominationCensusReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdf_file', models.FileField(upload_to='denomination_reports/', verbose_name='Census Report PDF')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('omeka_item_id', models.IntegerField(blank=True, null=True)),
                ('omeka_media_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('denomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='census_reports', to='census.denomination')),
            ],
            options={
                'verbose_name': 'Denomination Census Report',
                'verbose_name_plural': 'Denomination Census Reports',
            },
        ),
        migrations.CreateModel(
            name='HistoricalDenominationCensusReport',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('pdf_file', models.TextField(max_length=100, verbose_name='Census Report PDF')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('original_filename', models.CharField(blank=True, max_length=255)),
                ('omeka_item_id', models.IntegerField(blank=True, null=True)),
                ('omeka_media_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('denomination', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='census.denomination')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Denomination Census Report',
                'verbose_name_plural': 'historical Denomination Census Reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
