# Generated by Django 5.1.5 on 2025-03-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0017_censusschedule_box_historicalcensusschedule_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="censusschedule",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="notes",
            field=models.TextField(default=""),
        ),
        migrations.AlterField(
            model_name="censusschedule",
            name="box",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="box",
            field=models.CharField(default="", max_length=50),
        ),
    ]
