# Generated by Django 6.0.1 on 2026-03-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0017_denominationcensusreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusschedule',
            name='ai_transcription',
            field=models.JSONField(blank=True, help_text='Raw JSON response from agentic transcription of the census schedule image', null=True, verbose_name='AI Transcription'),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='ai_transcription',
            field=models.JSONField(blank=True, help_text='Raw JSON response from agentic transcription of the census schedule image', null=True, verbose_name='AI Transcription'),
        ),
    ]
