# Generated by Django 5.1.5 on 2025-03-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0018_censusschedule_notes_historicalcensusschedule_notes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="censusschedule",
            name="datascribe_original_image_path",
            field=models.CharField(
                default="",
                help_text="This record is read-only and not editable.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="censusschedule",
            name="omeka_storage_id",
            field=models.CharField(
                default="",
                help_text="This record is read-only and not editable.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="datascribe_original_image_path",
            field=models.CharField(
                default="",
                help_text="This record is read-only and not editable.",
                max_length=255,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicalcensusschedule",
            name="omeka_storage_id",
            field=models.CharField(
                default="",
                help_text="This record is read-only and not editable.",
                max_length=255,
            ),
            preserve_default=False,
        ),
    ]
