# Generated by Django 6.0.1 on 2026-03-30 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0018_censusschedule_ai_transcription_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='denomination',
            name='published_churches_count',
            field=models.IntegerField(blank=True, help_text='Number of churches reported in the published 1926 census volume', null=True, verbose_name='Published Churches Count'),
        ),
        migrations.AddField(
            model_name='historicaldenomination',
            name='published_churches_count',
            field=models.IntegerField(blank=True, help_text='Number of churches reported in the published 1926 census volume', null=True, verbose_name='Published Churches Count'),
        ),
    ]
