# Generated by Django 6.0.5 on 2026-05-11 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0019_denomination_published_churches_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusschedule',
            name='ai_notes',
            field=models.TextField(blank=True, help_text='Free-form observations from the AI transcriber about anomalies, illegibility, or decisions'),
        ),
        migrations.AddField(
            model_name='censusschedule',
            name='date_received',
            field=models.DateField(blank=True, help_text='Date the Census Bureau received this schedule (from receipt stamp)', null=True),
        ),
        migrations.AddField(
            model_name='censusschedule',
            name='denomination_code_stamp',
            field=models.CharField(blank=True, help_text="Full denomination code stamp in cursive (e.g., '0-1-3')", max_length=20),
        ),
        migrations.AddField(
            model_name='censusschedule',
            name='district_stamp',
            field=models.CharField(blank=True, help_text="Census Bureau district stamp (e.g., 'Denver, D')", max_length=100),
        ),
        migrations.AddField(
            model_name='censusschedule',
            name='marginalia',
            field=models.JSONField(blank=True, default=list, help_text='Array of {page_location, marginalia_transcription} for handwritten marks not captured elsewhere'),
        ),
        migrations.AddField(
            model_name='censusschedule',
            name='num_assistant_pastors',
            field=models.IntegerField(blank=True, help_text='Number of ordained ministers employed as assistant pastors (field 26)', null=True, verbose_name='Number of assistant pastors'),
        ),
        migrations.AddField(
            model_name='censusschedule',
            name='respondent_date_signed',
            field=models.CharField(blank=True, help_text='Date signed (YYYY-MM-DD or YYYY if partial)', max_length=10),
        ),
        migrations.AddField(
            model_name='censusschedule',
            name='respondent_name',
            field=models.CharField(blank=True, help_text='Signature of person furnishing information', max_length=255),
        ),
        migrations.AddField(
            model_name='censusschedule',
            name='respondent_po_address',
            field=models.CharField(blank=True, help_text='P.O. address of person furnishing information', max_length=255),
        ),
        migrations.AddField(
            model_name='censusschedule',
            name='respondent_title',
            field=models.CharField(blank=True, help_text='Official title of person furnishing information (e.g., Pastor, Clerk)', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='ai_notes',
            field=models.TextField(blank=True, help_text='Free-form observations from the AI transcriber about anomalies, illegibility, or decisions'),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='date_received',
            field=models.DateField(blank=True, help_text='Date the Census Bureau received this schedule (from receipt stamp)', null=True),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='denomination_code_stamp',
            field=models.CharField(blank=True, help_text="Full denomination code stamp in cursive (e.g., '0-1-3')", max_length=20),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='district_stamp',
            field=models.CharField(blank=True, help_text="Census Bureau district stamp (e.g., 'Denver, D')", max_length=100),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='marginalia',
            field=models.JSONField(blank=True, default=list, help_text='Array of {page_location, marginalia_transcription} for handwritten marks not captured elsewhere'),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='num_assistant_pastors',
            field=models.IntegerField(blank=True, help_text='Number of ordained ministers employed as assistant pastors (field 26)', null=True, verbose_name='Number of assistant pastors'),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='respondent_date_signed',
            field=models.CharField(blank=True, help_text='Date signed (YYYY-MM-DD or YYYY if partial)', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='respondent_name',
            field=models.CharField(blank=True, help_text='Signature of person furnishing information', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='respondent_po_address',
            field=models.CharField(blank=True, help_text='P.O. address of person furnishing information', max_length=255),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='respondent_title',
            field=models.CharField(blank=True, help_text='Official title of person furnishing information (e.g., Pastor, Clerk)', max_length=255),
        ),
    ]
