# Generated by Django 5.1.5 on 2025-03-24 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0019_censusschedule_datascribe_original_image_path_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censusschedule",
            name="box",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="censusschedule",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="box",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="notes",
            field=models.TextField(blank=True, default="", null=True),
        ),
    ]
