# Generated by Django 6.0.5 on 2026-06-08 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0020_censusschedule_ai_notes_censusschedule_date_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusschedule',
            name='human_transcription',
            field=models.JSONField(blank=True, help_text='The raw JSON response from the human transcribers of the census schedule image, available for comparison against AI transcriptions.', null=True, verbose_name='Original human transcription'),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='human_transcription',
            field=models.JSONField(blank=True, help_text='The raw JSON response from the human transcribers of the census schedule image, available for comparison against AI transcriptions.', null=True, verbose_name='Original human transcription'),
        ),
        migrations.AlterField(
            model_name='censusschedule',
            name='ai_transcription',
            field=models.JSONField(blank=True, help_text='Raw JSON response from agentic transcription of the census schedule image', null=True, verbose_name='AI transcription'),
        ),
        migrations.AlterField(
            model_name='historicalcensusschedule',
            name='ai_transcription',
            field=models.JSONField(blank=True, help_text='Raw JSON response from agentic transcription of the census schedule image', null=True, verbose_name='AI transcription'),
        ),
    ]
