# Generated by Django 5.1.5 on 2025-03-25 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0021_remove_historicalmembership_church_and_more"),
        ("location", "0008_alter_historicallocation_county_ahcb_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="historicalmembership",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Membership",
                "verbose_name_plural": "historical Membership",
            },
        ),
        migrations.AlterModelOptions(
            name="historicalreligiousbody",
            options={
                "get_latest_by": ("history_date", "history_id"),
                "ordering": ("-history_date", "-history_id"),
                "verbose_name": "historical Religious Body",
                "verbose_name_plural": "historical Religious Body",
            },
        ),
        migrations.AlterModelOptions(
            name="membership",
            options={"verbose_name": "Membership", "verbose_name_plural": "Membership"},
        ),
        migrations.AlterModelOptions(
            name="religiousbody",
            options={
                "verbose_name": "Religious Body",
                "verbose_name_plural": "Religious Body",
            },
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="denomination",
        ),
        migrations.RemoveField(
            model_name="censusschedule",
            name="location",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="denomination",
        ),
        migrations.RemoveField(
            model_name="historicalcensusschedule",
            name="location",
        ),
        migrations.AddField(
            model_name="historicalreligiousbody",
            name="denomination",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Selec the denomination associated with this religious body.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="census.denomination",
            ),
        ),
        migrations.AddField(
            model_name="religiousbody",
            name="denomination",
            field=models.ForeignKey(
                help_text="Selec the denomination associated with this religious body.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="census.denomination",
            ),
        ),
        migrations.AlterField(
            model_name="censusschedule",
            name="box",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="censusschedule",
            name="datascribe_original_image_path",
            field=models.CharField(
                max_length=255, verbose_name="DataScribe Original Image Path"
            ),
        ),
        migrations.AlterField(
            model_name="censusschedule",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="censusschedule",
            name="omeka_storage_id",
            field=models.CharField(max_length=255, verbose_name="Omeka Storage ID"),
        ),
        migrations.AlterField(
            model_name="clergy",
            name="num_other_churches_served",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="box",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="datascribe_original_image_path",
            field=models.CharField(
                max_length=255, verbose_name="DataScribe Original Image Path"
            ),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="omeka_storage_id",
            field=models.CharField(max_length=255, verbose_name="Omeka Storage ID"),
        ),
        migrations.AlterField(
            model_name="historicalclergy",
            name="num_other_churches_served",
            field=models.PositiveIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="female_members",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Female Members"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="male_members",
            field=models.PositiveIntegerField(default=0, verbose_name="Male Members"),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="members_13_and_older",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Members 13 and Older"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="members_under_13",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Members Under 13"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_administrators",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Administrators"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_elementary_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Elementary Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_elementary_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Elementary Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_secondary_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Secondary Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_secondary_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Secondary Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="religious_body",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="census.religiousbody",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="sunday_school_num_officers_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Officers/Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="sunday_school_num_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="vbs_num_officers_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Officers/Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="vbs_num_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The name of the church as it appears in the census record.",
                max_length=255,
                null=True,
                verbose_name="Local Church Name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="num_edifices",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Number of edifices"
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="urban_rural_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Urban/rural code"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="census_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership_details",
                to="census.censusschedule",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="female_members",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Female Members"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="male_members",
            field=models.PositiveIntegerField(default=0, verbose_name="Male Members"),
        ),
        migrations.AlterField(
            model_name="membership",
            name="members_13_and_older",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Members 13 and Older"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="members_under_13",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Members Under 13"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_administrators",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Administrators"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_elementary_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Elementary Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_elementary_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Elementary Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_secondary_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Secondary Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_secondary_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Secondary Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="religious_body",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="membership",
                to="census.religiousbody",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="sunday_school_num_officers_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Officers/Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="sunday_school_num_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="vbs_num_officers_teachers",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Officers/Teachers"
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="vbs_num_scholars",
            field=models.PositiveIntegerField(
                default=0, null=True, verbose_name="Number of Scholars"
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="census_record",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="church_details",
                to="census.censusschedule",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.location",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The name of the church as it appears in the census record.",
                max_length=255,
                null=True,
                verbose_name="Local Church Name",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="num_edifices",
            field=models.PositiveIntegerField(
                blank=True, default=0, null=True, verbose_name="Number of edifices"
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="urban_rural_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Urban/rural code"
            ),
        ),
    ]
