# Generated by Django 6.0.5 on 2026-07-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0021_censusschedule_human_transcription_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censusschedule",
            name="transcription_status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("needs_review", "Imported - Needs Review"),
                    ("completed", "Ready for Review"),
                    ("approved", "Approved"),
                ],
                default="unassigned",
                max_length=20,
                verbose_name="Transcription Status",
            ),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="transcription_status",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("assigned", "Assigned"),
                    ("in_progress", "In Progress"),
                    ("needs_review", "Imported - Needs Review"),
                    ("completed", "Ready for Review"),
                    ("approved", "Approved"),
                ],
                default="unassigned",
                max_length=20,
                verbose_name="Transcription Status",
            ),
        ),
    ]
