# Generated by Django 5.1.5 on 2025-03-25 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0022_alter_historicalmembership_options_and_more"),
        ("location", "0008_alter_historicallocation_county_ahcb_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="censusschedule",
            name="resource_id",
            field=models.IntegerField(unique=True, verbose_name="Record ID"),
        ),
        migrations.AlterField(
            model_name="censusschedule",
            name="schedule_id",
            field=models.CharField(max_length=50, verbose_name="Schedule ID"),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="resource_id",
            field=models.IntegerField(db_index=True, verbose_name="Record ID"),
        ),
        migrations.AlterField(
            model_name="historicalcensusschedule",
            name="schedule_id",
            field=models.CharField(max_length=50, verbose_name="Schedule ID"),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="benevolences",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="expenses",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Use the magnifying class to the right to search for a location. Do not manually edit this number.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="location.location",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The name of the church as it appears in the census record.",
                max_length=255,
                null=True,
                verbose_name="Local church name",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="residence_debt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="residence_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="total_expenditures",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="benevolences",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="expenses",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="location",
            field=models.ForeignKey(
                blank=True,
                help_text="Use the magnifying class to the right to search for a location. Do not manually edit this number.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="location.location",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="name",
            field=models.CharField(
                blank=True,
                help_text="The name of the church as it appears in the census record.",
                max_length=255,
                null=True,
                verbose_name="Local church name",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="residence_debt",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="residence_value",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="total_expenditures",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=0, max_digits=12
            ),
        ),
    ]
