# Generated by Django 6.0.5 on 2026-08-03 15:53

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models
from django.db.models import Q


def _bulk_create_outputs(Output, outputs):
    batch = []
    for output in outputs:
        batch.append(output)
        if len(batch) == 500:
            Output.objects.bulk_create(batch)
            batch = []
    if batch:
        Output.objects.bulk_create(batch)


def migrate_legacy_transcriptions(apps, schema_editor):
    CensusSchedule = apps.get_model("census", "CensusSchedule")
    ScheduleTranscription = apps.get_model("census", "ScheduleTranscription")
    TranscriptionRun = apps.get_model("census", "TranscriptionRun")

    human_schedules = CensusSchedule.objects.filter(human_transcription__isnull=False)
    if human_schedules.exists():
        human_run = TranscriptionRun.objects.create(
            key="human-snapshot",
            kind="human_snapshot",
            metadata={"migrated_from": "CensusSchedule.human_transcription"},
        )
        _bulk_create_outputs(
            ScheduleTranscription,
            (
                ScheduleTranscription(
                    census_schedule_id=schedule.pk,
                    run_id=human_run.pk,
                    data=schedule.human_transcription,
                )
                for schedule in human_schedules.only(
                    "pk", "human_transcription"
                ).iterator(chunk_size=500)
            ),
        )

    agent_schedules = CensusSchedule.objects.filter(
        Q(ai_transcription__isnull=False) | ~Q(ai_notes="")
    )
    if agent_schedules.exists():
        agent_run = TranscriptionRun.objects.create(
            key="legacy-agent-transcription",
            kind="agent",
            metadata={
                "migrated_from": [
                    "CensusSchedule.ai_transcription",
                    "CensusSchedule.ai_notes",
                ]
            },
        )

        def agent_outputs():
            for schedule in agent_schedules.only(
                "pk", "ai_transcription", "ai_notes"
            ).iterator(chunk_size=500):
                raw_data = schedule.ai_transcription
                if isinstance(raw_data, dict):
                    data = dict(raw_data)
                elif raw_data is None:
                    data = {}
                else:
                    data = {"transcription": raw_data}
                if schedule.ai_notes:
                    data["ai_notes"] = schedule.ai_notes
                yield ScheduleTranscription(
                    census_schedule_id=schedule.pk,
                    run_id=agent_run.pk,
                    data=data,
                )

        _bulk_create_outputs(ScheduleTranscription, agent_outputs())


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0022_alter_censusschedule_transcription_status_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TranscriptionRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable identifier for this run, such as walter-gemini-2026-08-26.",
                        max_length=120,
                        unique=True,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("human_snapshot", "Human snapshot"),
                            ("agent", "Agent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional run-level provenance such as model, prompt, or code versions.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at", "key"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalTranscriptionRun",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "key",
                    models.SlugField(
                        help_text="Stable identifier for this run, such as walter-gemini-2026-08-26.",
                        max_length=120,
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("human_snapshot", "Human snapshot"),
                            ("agent", "Agent"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Optional run-level provenance such as model, prompt, or code versions.",
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical transcription run",
                "verbose_name_plural": "historical transcription runs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalScheduleTranscription",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Raw transcription JSON. Agent notes belong inside this object."
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "census_schedule",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="census.censusschedule",
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="census.transcriptionrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical schedule transcription",
                "verbose_name_plural": "historical schedule transcriptions",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="ScheduleTranscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(
                        help_text="Raw transcription JSON. Agent notes belong inside this object."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "census_schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transcriptions",
                        to="census.censusschedule",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="schedule_transcriptions",
                        to="census.transcriptionrun",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "pk"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("census_schedule", "run"),
                        name="unique_schedule_transcription_run",
                    )
                ],
            },
        ),
        migrations.RunPython(
            migrate_legacy_transcriptions,
            migrations.RunPython.noop,
        ),
    ]
