# Generated by Django 6.0.5 on 2026-08-06 12:46

import census.models
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0023_transcription_runs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduletranscription',
            name='census_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcriptions', to='census.censusschedule'),
        ),
        migrations.CreateModel(
            name='HistoricalTranscriptionBatch',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('provider', models.CharField(default='anthropic', max_length=30)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('submitting', 'Submitting'), ('in_progress', 'In progress'), ('collecting', 'Collecting'), ('ended', 'Ended'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('needs_recovery', 'Needs manual recovery')], db_index=True, default='queued', max_length=30)),
                ('provider_batch_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('encoded_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('request_counts', models.JSONField(blank=True, default=dict)),
                ('provider_snapshot', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider_ended_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='census.transcriptionrun')),
            ],
            options={
                'verbose_name': 'historical transcription batch',
                'verbose_name_plural': 'historical transcription batchs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TranscriptionBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='anthropic', max_length=30)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('submitting', 'Submitting'), ('in_progress', 'In progress'), ('collecting', 'Collecting'), ('ended', 'Ended'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('needs_recovery', 'Needs manual recovery')], db_index=True, default='queued', max_length=30)),
                ('provider_batch_id', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('encoded_size_bytes', models.PositiveBigIntegerField(default=0)),
                ('request_counts', models.JSONField(blank=True, default=dict)),
                ('provider_snapshot', models.JSONField(blank=True, null=True)),
                ('error', models.JSONField(blank=True, null=True)),
                ('lease_token', models.UUIDField(blank=True, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('provider_expires_at', models.DateTimeField(blank=True, null=True)),
                ('provider_ended_at', models.DateTimeField(blank=True, null=True)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcription_batches', to='census.transcriptionrun')),
            ],
            options={
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalTranscriptionJob',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('custom_id', models.CharField(db_index=True, default=census.models.transcription_job_custom_id, editable=False, max_length=64)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('submitted', 'Submitted'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('invalid', 'Invalid response'), ('needs_recovery', 'Needs manual recovery')], db_index=True, default='queued', max_length=30)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=120, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=60, null=True)),
                ('usage', models.JSONField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_creation_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_read_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(blank=True, editable=False)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('census_schedule', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='census.censusschedule')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='census.transcriptionrun')),
                ('batch', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='census.transcriptionbatch')),
            ],
            options={
                'verbose_name': 'historical transcription job',
                'verbose_name_plural': 'historical transcription jobs',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_id', models.CharField(default=census.models.transcription_job_custom_id, editable=False, max_length=64, unique=True)),
                ('attempt', models.PositiveIntegerField(default=1)),
                ('state', models.CharField(choices=[('queued', 'Queued'), ('preparing', 'Preparing'), ('submitted', 'Submitted'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired'), ('canceled', 'Canceled'), ('invalid', 'Invalid response'), ('needs_recovery', 'Needs manual recovery')], db_index=True, default='queued', max_length=30)),
                ('raw_result', models.JSONField(blank=True, null=True)),
                ('provider_message_id', models.CharField(blank=True, max_length=120, null=True)),
                ('stop_reason', models.CharField(blank=True, max_length=60, null=True)),
                ('usage', models.JSONField(blank=True, null=True)),
                ('input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('output_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_creation_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('cache_read_input_tokens', models.PositiveIntegerField(blank=True, null=True)),
                ('error_type', models.CharField(blank=True, max_length=100)),
                ('error_message', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='census.transcriptionbatch')),
                ('census_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcription_jobs', to='census.censusschedule')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transcription_jobs', to='census.transcriptionrun')),
            ],
            options={
                'ordering': ['queued_at', 'pk'],
            },
        ),
        migrations.AddIndex(
            model_name='transcriptionbatch',
            index=models.Index(fields=['state', 'lease_expires_at'], name='census_tran_state_5816ee_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionbatch',
            index=models.Index(fields=['run', 'state'], name='census_tran_run_id_1fc9fa_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionjob',
            index=models.Index(fields=['state', 'queued_at'], name='census_tran_state_44eb5a_idx'),
        ),
        migrations.AddIndex(
            model_name='transcriptionjob',
            index=models.Index(fields=['run', 'state'], name='census_tran_run_id_fa8ef2_idx'),
        ),
        migrations.AddConstraint(
            model_name='transcriptionjob',
            constraint=models.UniqueConstraint(fields=('census_schedule', 'run', 'attempt'), name='unique_schedule_run_attempt'),
        ),
        migrations.AddConstraint(
            model_name='transcriptionjob',
            constraint=models.UniqueConstraint(condition=models.Q(('state__in', ['queued', 'preparing', 'submitted', 'succeeded', 'needs_recovery'])), fields=('census_schedule', 'run'), name='unique_active_schedule_run_job'),
        ),
    ]
