# Generated by Django 5.1.7 on 2025-03-26 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0023_alter_censusschedule_resource_id_and_more"),
        ("location", "0008_alter_historicallocation_county_ahcb_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="religiousbody",
            index=models.Index(
                fields=["denomination"], name="census_reli_denomin_652bc8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="religiousbody",
            index=models.Index(
                fields=["location"], name="census_reli_locatio_f3c697_idx"
            ),
        ),
    ]
