# Generated by Django 5.1.7 on 2025-05-09 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("census", "0024_religiousbody_census_reli_denomin_652bc8_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="clergy",
            name="serving_congregation",
            field=models.CharField(
                blank=True,
                help_text="Can be Yes, No, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Pastor serving congregation",
            ),
        ),
        migrations.AddField(
            model_name="historicalclergy",
            name="serving_congregation",
            field=models.CharField(
                blank=True,
                help_text="Can be Yes, No, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Pastor serving congregation",
            ),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="total_members_by_age",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Total Members by Age",
            ),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="total_members_by_sex",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Total Members by Sex",
            ),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="weekday_num_officers_teachers",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Week-day Religious Schools - Number of Officers/Teachers",
            ),
        ),
        migrations.AddField(
            model_name="historicalmembership",
            name="weekday_num_scholars",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Week-day Religious Schools - Number of Scholars",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="total_members_by_age",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Total Members by Age",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="total_members_by_sex",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Total Members by Sex",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="weekday_num_officers_teachers",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Week-day Religious Schools - Number of Officers/Teachers",
            ),
        ),
        migrations.AddField(
            model_name="membership",
            name="weekday_num_scholars",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Week-day Religious Schools - Number of Scholars",
            ),
        ),
        migrations.AlterField(
            model_name="clergy",
            name="college",
            field=models.CharField(
                blank=True,
                help_text="Can contain a college name, MISSING, or ILLEGIBLE",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clergy",
            name="name",
            field=models.CharField(
                help_text="Can contain a name, MISSING, or ILLEGIBLE", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="clergy",
            name="num_other_churches_served",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Number of other churches served",
            ),
        ),
        migrations.AlterField(
            model_name="clergy",
            name="theological_seminary",
            field=models.CharField(
                blank=True,
                help_text="Can contain a seminary name, MISSING, or ILLEGIBLE",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclergy",
            name="college",
            field=models.CharField(
                blank=True,
                help_text="Can contain a college name, MISSING, or ILLEGIBLE",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalclergy",
            name="name",
            field=models.CharField(
                help_text="Can contain a name, MISSING, or ILLEGIBLE", max_length=255
            ),
        ),
        migrations.AlterField(
            model_name="historicalclergy",
            name="num_other_churches_served",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Number of other churches served",
            ),
        ),
        migrations.AlterField(
            model_name="historicalclergy",
            name="theological_seminary",
            field=models.CharField(
                blank=True,
                help_text="Can contain a seminary name, MISSING, or ILLEGIBLE",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="female_members",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Female Members",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="male_members",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Male Members",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="members_13_and_older",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Members 13 and Older",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="members_under_13",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Members Under 13",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_administrators",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Parochial Schools - Number of Administrators",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_elementary_scholars",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Parochial Schools - Number of Elementary Scholars",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_elementary_teachers",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Parochial Schools - Number of Elementary Teachers",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_secondary_scholars",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Parochial Schools - Number of Secondary Scholars",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="parochial_num_secondary_teachers",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Parochial Schools - Number of Secondary Teachers",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="sunday_school_num_officers_teachers",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Sunday Schools - Number of Officers/Teachers",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="sunday_school_num_scholars",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Sunday Schools - Number of Scholars",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="vbs_num_officers_teachers",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Vacation Bible Schools - Number of Officers/Teachers",
            ),
        ),
        migrations.AlterField(
            model_name="historicalmembership",
            name="vbs_num_scholars",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Vacation Bible Schools - Number of Scholars",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="benevolences",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Benevolences",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="denomination",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="Select the denomination associated with this religious body.",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="census.denomination",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="edifice_debt",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Debt on church edifices",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="edifice_value",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Value of church edifices",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="expenses",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="has_pastors_residence",
            field=models.CharField(
                blank=True,
                help_text="Can be Yes, No, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Ownership of pastor's residence",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="num_edifices",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Number of edifices",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="residence_debt",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Debt on pastor's residence",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="residence_value",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Value of pastor's residence",
            ),
        ),
        migrations.AlterField(
            model_name="historicalreligiousbody",
            name="total_expenditures",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Total annual expenditures",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="female_members",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Female Members",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="male_members",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Male Members",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="members_13_and_older",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Members 13 and Older",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="members_under_13",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Members Under 13",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_administrators",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Parochial Schools - Number of Administrators",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_elementary_scholars",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Parochial Schools - Number of Elementary Scholars",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_elementary_teachers",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Parochial Schools - Number of Elementary Teachers",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_secondary_scholars",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Parochial Schools - Number of Secondary Scholars",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="parochial_num_secondary_teachers",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Parochial Schools - Number of Secondary Teachers",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="sunday_school_num_officers_teachers",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Sunday Schools - Number of Officers/Teachers",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="sunday_school_num_scholars",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Sunday Schools - Number of Scholars",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="vbs_num_officers_teachers",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Vacation Bible Schools - Number of Officers/Teachers",
            ),
        ),
        migrations.AlterField(
            model_name="membership",
            name="vbs_num_scholars",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Vacation Bible Schools - Number of Scholars",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="benevolences",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Benevolences",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="denomination",
            field=models.ForeignKey(
                help_text="Select the denomination associated with this religious body.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="census.denomination",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="edifice_debt",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Debt on church edifices",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="edifice_value",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Value of church edifices",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="expenses",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Expenses",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="has_pastors_residence",
            field=models.CharField(
                blank=True,
                help_text="Can be Yes, No, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Ownership of pastor's residence",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="num_edifices",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Number of edifices",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="residence_debt",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Debt on pastor's residence",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="residence_value",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Value of pastor's residence",
            ),
        ),
        migrations.AlterField(
            model_name="religiousbody",
            name="total_expenditures",
            field=models.CharField(
                blank=True,
                help_text="Can contain numeric values, MISSING, or ILLEGIBLE",
                max_length=50,
                null=True,
                verbose_name="Total annual expenditures",
            ),
        ),
    ]
