# Generated by Django 6.0.5 on 2026-08-20 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0024_alter_scheduletranscription_census_schedule_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outcome', models.CharField(choices=[('retained_current', 'Kept current canonical data'), ('promoted_candidate', 'Promoted one candidate'), ('mixed', 'Combined current and candidate data')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('canonical_before', models.JSONField()),
                ('canonical_after', models.JSONField()),
                ('before_fingerprint', models.CharField(max_length=64)),
                ('after_fingerprint', models.CharField(max_length=64)),
                ('decisions', models.JSONField(default=dict)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('census_schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliations', to='census.censusschedule')),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='census.schedulereconciliation')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schedule_reconciliations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disposition', models.CharField(choices=[('accepted', 'Accepted'), ('incorporated', 'Partially incorporated'), ('rejected', 'Rejected'), ('superseded', 'Superseded')], max_length=20)),
                ('transcription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_sources', to='census.scheduletranscription')),
                ('reconciliation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sources', to='census.schedulereconciliation')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('reconciliation', 'transcription'), name='unique_reconciliation_transcription_source')],
            },
        ),
    ]
