# Generated by Django 6.0.5 on 2026-08-24 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("census", "0025_schedulereconciliation_reconciliationsource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedulereconciliation",
            name="outcome",
            field=models.CharField(
                choices=[
                    ("retained_current", "Kept canonical data"),
                    ("promoted_candidate", "Promoted one evidence source"),
                    ("mixed", "Combined evidence and reviewer edits"),
                    ("rolled_back", "Restored previous canonical data"),
                ],
                max_length=30,
            ),
        ),
    ]
