# Generated by Django 6.1.1 on 2026-09-09 15:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0027_needs_review_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconciliationsource',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 9, 9, 15, 7, 16, 786879, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
