# Generated by Django 6.1.1 on 2026-09-09 15:23

import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0028_reconciliationsource_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='censusschedule',
            name='title_sort_key',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.text.Lower(models.Func(models.Func(models.F('schedule_title'), models.Value('[ :]*\\d+[a-z]?\\s*$'), models.Value(''), function='regexp_replace'), models.Value('[ :]+$'), models.Value(''), function='regexp_replace')), models.Value('|'), models.Func(django.db.models.functions.comparison.Coalesce(models.Func(models.F('schedule_title'), models.Value('(\\d+)[a-z]?\\s*$'), function='substring'), models.Value('')), models.Value(8), models.Value('0'), function='lpad', output_field=models.CharField(max_length=8)), django.db.models.functions.comparison.Coalesce(models.Func(models.F('schedule_title'), models.Value('\\d+([a-z]?)\\s*$'), function='substring'), models.Value('')), output_field=models.CharField(max_length=300)), output_field=models.CharField(max_length=300)),
        ),
        migrations.AddField(
            model_name='historicalcensusschedule',
            name='title_sort_key',
            field=models.GeneratedField(db_index=True, db_persist=True, expression=django.db.models.functions.text.Concat(django.db.models.functions.text.Lower(models.Func(models.Func(models.F('schedule_title'), models.Value('[ :]*\\d+[a-z]?\\s*$'), models.Value(''), function='regexp_replace'), models.Value('[ :]+$'), models.Value(''), function='regexp_replace')), models.Value('|'), models.Func(django.db.models.functions.comparison.Coalesce(models.Func(models.F('schedule_title'), models.Value('(\\d+)[a-z]?\\s*$'), function='substring'), models.Value('')), models.Value(8), models.Value('0'), function='lpad', output_field=models.CharField(max_length=8)), django.db.models.functions.comparison.Coalesce(models.Func(models.F('schedule_title'), models.Value('\\d+([a-z]?)\\s*$'), function='substring'), models.Value('')), output_field=models.CharField(max_length=300)), output_field=models.CharField(max_length=300)),
        ),
    ]
