# Generated by Django 6.1.1 on 2026-10-07 16:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('census', '0029_censusschedule_title_sort_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RunPublication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True)),
                ('state', models.CharField(choices=[('previewing', 'Previewing'), ('ready', 'Ready to publish'), ('publishing', 'Publishing'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='previewing', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to='census.transcriptionrun')),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='RunPublicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.CharField(blank=True, choices=[('promote', 'Publish run output'), ('reconciled', 'Keep: reconciled by a person'), ('edited', 'Keep: agent version edited'), ('no_output', 'Skip: no output')], max_length=20)),
                ('overwrite_warning', models.BooleanField(default=False)),
                ('outcome', models.CharField(blank=True, choices=[('published', 'Published'), ('approved', 'Kept and approved'), ('kept', 'Kept unchanged'), ('skipped', 'Skipped'), ('failed', 'Failed')], max_length=20)),
                ('detail', models.TextField(blank=True)),
                ('census_schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='census.censusschedule')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='census.runpublication')),
            ],
            options={
                'ordering': ['pk'],
            },
        ),
        migrations.AddIndex(
            model_name='runpublication',
            index=models.Index(fields=['state', 'created_at'], name='census_runp_state_7a9c14_idx'),
        ),
        migrations.AddIndex(
            model_name='runpublicationitem',
            index=models.Index(fields=['publication', 'case'], name='census_runp_publica_2d98b6_idx'),
        ),
        migrations.AddIndex(
            model_name='runpublicationitem',
            index=models.Index(fields=['publication', 'outcome'], name='census_runp_publica_1dbed4_idx'),
        ),
        migrations.AddConstraint(
            model_name='runpublicationitem',
            constraint=models.UniqueConstraint(fields=('publication', 'census_schedule'), name='unique_publication_schedule'),
        ),
    ]
