# Generated by Django 5.1.4 on 2024-12-19 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("church", "0001_initial"),
        ("education", "0002_alter_sundayschool_church_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vacationbibleschool",
            name="church",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vacation_bible_school",
                to="church.church",
            ),
        ),
    ]
