# Generated by Django 6.0.1 on 2026-04-20 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('census', '0019_denomination_published_churches_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the church or data point', max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=255)),
                ('county', models.CharField(blank=True, max_length=255)),
                ('state', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, db_index=True, help_text='Identifier for the dataset this point belongs to', max_length=255)),
                ('data', models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value data for this point (e.g., pastor_name, gender, notes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('census_schedule', models.ForeignKey(blank=True, help_text='Link to a census schedule record, if applicable', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_layers', to='census.censusschedule')),
            ],
            options={
                'verbose_name': 'Data Layer',
                'verbose_name_plural': 'Data Layers',
                'ordering': ['source', 'title'],
                'indexes': [models.Index(fields=['source'], name='datalayers__source_2256c9_idx'), models.Index(fields=['state', 'county'], name='datalayers__state_9c967f_idx')],
            },
        ),
    ]
