# Generated by Django 6.0.1 on 2026-04-20 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0001_initial'),
        ('location', '0004_populate_geographic_hierarchy'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayer',
            name='county_ref',
            field=models.ForeignKey(blank=True, help_text='Matched county from location data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_layers', to='location.county'),
        ),
        migrations.AddField(
            model_name='datalayer',
            name='populated_place_ref',
            field=models.ForeignKey(blank=True, help_text='Matched populated place from location data', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='data_layers', to='location.populatedplace'),
        ),
    ]
