# Generated by Django 6.0.1 on 2026-04-21 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0002_datalayer_county_ref_datalayer_populated_place_ref'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataLayerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text="URL-safe identifier matching the DataLayer.source field (e.g., 'dc-churches')", max_length=255, unique=True)),
                ('title', models.CharField(help_text='Display title for the visualization', max_length=255)),
                ('abstract', models.TextField(blank=True, help_text='Brief description of this dataset')),
                ('author', models.CharField(blank=True, max_length=255)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('doi', models.URLField(blank=True, help_text='Digital Object Identifier')),
                ('thumbnail_image', models.ImageField(blank=True, null=True, upload_to='datalayers/thumbnails/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Data Layer Source',
                'verbose_name_plural': 'Data Layer Sources',
                'ordering': ['-published_date'],
            },
        ),
    ]
