# Generated by Django 6.0.1 on 2026-04-21 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datalayers', '0003_datalayersource'),
    ]

    operations = [
        migrations.AddField(
            model_name='datalayersource',
            name='content',
            field=models.TextField(blank=True, help_text='Full writeup/essay in Markdown, displayed below the map'),
        ),
        migrations.AlterField(
            model_name='datalayersource',
            name='abstract',
            field=models.TextField(blank=True, help_text='Brief description for the visualization card'),
        ),
    ]
